pipeline:
  name: sample-react-app
  identifier: samplereactapp
  projectIdentifier: DhrubaCI
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: build test and run
        identifier: build_test_and_run
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: install node modules
                  identifier: install_node_modules
                  spec:
                    connectorRef: account.harnessImage
                    image: harnesscommunity/sample-react-app:latest
                    shell: Sh
                    command: npm install
              - step:
                  type: Run
                  name: create image
                  identifier: create_image
                  spec:
                    connectorRef: account.harnessImage
                    image: node:15.4
                    shell: Sh
                    command: |-
                      touch Dockerfile
                      cat > Dockerfile <<- EOM
                      FROM node:15.4 as build 
                      WORKDIR /react-app
                      COPY package*.json .
                      RUN npm install
                      COPY . .
                      RUN npm run build
                      FROM nginx:1.19
                      COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
                      COPY --from=build /react-app/build /usr/share/nginx/html
                      EOM
                      cat Dockerfile
              - step:
                  type: BuildAndPushDockerRegistry
                  name: build and push to docker
                  identifier: build_and_push_to_docker
                  spec:
                    connectorRef: account.harnessImage
                    repo: harnesscommunity/react-testing
                    tags:
                      - latest
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: dhrubaaccountconnector
        repoName: sample-react-app-ci
        build: <+input>
